//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanalMF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorumlu
    {
        public int SorumluId { get; set; }
        public string SAdSoyad { get; set; }
        public string SGorevi { get; set; }
        public decimal SMaas { get; set; }
        public string SorumluGorevSayisi { get; set; }
        public int YayinYayinId { get; set; }
    
        public virtual Yayin Yayin { get; set; }
    }
}
